grammar = {
    "program": [["@", "statement", "program"]],
    "statement": [["assignment"], ["print"]],
    "assignment": [["WORD", "ASSIGN", "query"],
                   ["WORD", "ASSIGN", "expression"]],
    "query": [["LEFTBRACE", "STAR", "RIGHTBRACE"],
              ["LEFTBRACE", "filter", "query", "RIGHTBRACE"],
              ["filter", "query"],
              ["filter"],
              ["@"]],
    "print": [["PRINT", "LEFTP", "query", "RIGHTP"],
              ["PRINT", "LEFTP", "WORD", "RIGHTP"]],
    "expression": [["expression", "OPERAND", "expression"],
                   ["query"],
                   ["WORD"]],
    "filter": [["destination"], ["time"],
               ["subject"], ["property"],
               ["content"], ["sorting"],
               ["folder"]],
    "destination": [["to"], ["from"], ["cc"]],
    "time": [["TIME", "datevalue"]],
    "subject": [["SUBJECT", "subjectvalue"]],
    "sorting": [["SORTBY", "sortingvalue"]],
    "folder": [["FOLDER", "foldervalue"]],
    "property": [["forwarded"], ["read"]],
    "content": [["body"], ["attachments"]],
    "to": [["TO", "destinationvalue"]],
    "from": [["FROM", "destinationvalue"]],
    "cc": [["CC", "destinationvalue"]],
    "forwarded": [["FORWARDED", "BOOLVALUE"]],
    "read": [["READ", "BOOLVALUE"]],
    "body": [["BODY", "bodyvalue"]],
    "attachments": [["ATTACHMENTS", "attachementsvalue"]],
    "datevalue": [["DATE"], ["DATE", "STAR", "DATE"],
                  ["DATE", "STAR"], ["STAR", "DATE"],
                  ["STAR", "DAY"], ["DAY", "STAR"],
                  ["STAR", "YEAR"], ["YEAR", "STAR"]],
    "subjectvalue": [["wordlist", "STRING"]],
    "sortingvalue": [["PARAMETER", "SORTVALUE"]],
    "foldervalue": [["STRING"]],  # TO BE DISCUSSED
    "destinationvalue": [["wordlist"], ["EMAIL"], ["STRING"],
                         ["WORD"], ["STAR"]],
    "bodyvalue": [["wordlist"], ["WORD"], ["STRING"]],
    "attachmentsvalue": [["BOOLVALUE"], ["STRING"],
                         ["WORD"], ["INT"], ["INTEVRAL"]],
    # FEXTENSION TO BE DISSCUSED
    "wordlist": [["WORD", "wordlist"], ["WORD"], ["@"]]
}


print(grammar[str][0][0], grammar["read"][0][0])